### ISSUE TITLE
Perbaiki Responsif card di main.css

### ISSUE THREAD

**Issue by Daffabot** [handrathej/handrathej.github.io#1]
buat card nya itu nggak responsif mau di hp yang gw coba vivo Y91C ataupun di PC desktop.
-Di mobile cardnya terpotong
-Di pc cardnya kekecilan

jadi di main.css jangan cuma atur style di lebar layar 640px saja, tapi di lebar layar yang lainnya juga.

dan lebih baik memakai min-width daripada max-device-width
seperti contoh ini
```css
@media screen and (min-width: 550px) {
  .card {
    grid-column: span 4;
  }
}
  @media screen and (min-width: 760px) {
    .card {
      width: 350px;
      margin: 10 0px;
    }
  }
    @media screen and (min-width: 960px) {
		.card {
			  margin: 5px 100px;
		}
	}
``` 
Kau atur2 sendiri stylenya diatas biar responsif
